
[tool.poetry]
name = "snopes-rating-bot"
version = "0.1.0"
description = "snopes rating bot"
authors = ["endail"]

[tool.poetry.dependencies]
python = "3.10.2"
htmldom = "2.0"
replit = "3.2.4"
tweepy = "4.5.0"
